version: '3.2'
services:
    locust:
        container_name: locust
        build: .
        image: jackvasc/locust
        tty: true
        ports:
            - '8089:8089'
        environment:
          - ATTACKED_HOST=${ATTACKED_HOST}
          - LOCUST_OPTS=${LOCUST_OPTS}
          - SPEEDUP_REQUEST=${SPEEDUP_REQUEST}
        extra_hosts:
          - "speedup.local.com:192.168.122.57"
