apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: speedup-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: speedup.local.com
    http:
      paths:
      - path: /service01(/|$)(.*)
        backend:
          serviceName: service01
          servicePort: 8080
      - path: /service02(/|$)(.*)
        backend:
          serviceName: service02
          servicePort: 8080
      - path: /service03(/|$)(.*)
        backend:
          serviceName: service03
          servicePort: 8080
      - path: /service04(/|$)(.*)
        backend:
          serviceName: service04
          servicePort: 8080