apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service01
spec:
  hosts:
    - "*"
  gateways:
    - service-gateway
  http:
    - route:
        - destination:
            port:
              number: 8080
            host: service01
      match:
      - uri:
          prefix: /service01
      rewrite:
          uri: "/"
      # fault:
      #   delay:
      #     percent: 100
      #     fixedDelay: 5s
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service02
spec:
  hosts:
    - "*"
  gateways:
    - service-gateway
  http:
    - route:
        - destination:
            port:
              number: 8080
            host: service02
      match:
      - uri:
          prefix: /service02
      rewrite:
          uri: "/"
      # fault:
      #   delay:
      #     percent: 100
      #     fixedDelay: 5s
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service03
spec:
  hosts:
    - "*"
  gateways:
    - service-gateway
  http:
    - route:
        - destination:
            port:
              number: 8080
            host: service03
      match:
      - uri:
          prefix: /service03
      rewrite:
          uri: "/"
      # fault:
      #   delay:
      #     percent: 100
      #     fixedDelay: 5s
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service04
spec:
  hosts:
    - "service04"
  http:
    - route:
        - destination:
            port:
              number: 8080
            host: service04
      # fault:
      #   delay:
      #     percent: 100
      #     fixedDelay: 5s